// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgkipojbdrvnrqfddeab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNna2lwb2piZHJ2bnJxZmRkZWFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzE5NjIsImV4cCI6MjA2NzQwNzk2Mn0.Fq7HfpfqDFbIsdXp9cqF4bTr3HMX2EWB7WbTsFQdLOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    // Optimize auth for faster loading
    storageKey: 'supabase.auth.token',
    debug: false
  },
  global: {
    headers: {
      'x-client-info': 'autogestor-web',
      'Cache-Control': 'no-cache',
      'Pragma': 'no-cache'
    },
    // Add timeout for faster failures
    fetch: (url, options = {}) => {
      return fetch(url, {
        ...options,
        signal: AbortSignal.timeout(8000), // 8 second timeout
      });
    }
  },
  db: {
    schema: 'public'
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});